#pragma once

#include <basis/seadTypes.h>

enum LightType
{
    cLightType_FireBall = 0,
    cLightType_IceBall,
    cLightType_InvincibilityStar,
    cLightType_LiftLightBlock,
    cLightType_Torch_Underground,
    cLightType_Torch_GhostHouse,
    cLightType_Flashlight_Underground,
    cLightType_Flashlight_GhostHouse,
    cLightType_YoshiChibiLight,
    cLightType_YoshiChibiLight_Egg,
    cLightType_LiftHalfRotateLight,
    cLightType_DeepSeaLight,
    cLightType_Bilikyu,
    cLightType_FireSnake,
    cLightType_LineTrainHeadlight,
    cLightType_Poltergeist,
    cLightType_MouseEye, // "Chuu chuu's eye"
    cLightType_SearchKillerExplosion,
    cLightType_Teresa,
    cLightType_BigTeresa,
    cLightType_FirePillar,
    cLightType_Fishbone,
    cLightType_LightKurage,
    cLightType_Burner,
    cLightType_Bomhei,
    cLightType_Chouchin, // a.k.a. ankou
    cLightType_KazanRock,
    cLightType_FireBarL,
    cLightType_FireBarS,
    cLightType_Bubble,
    cLightType_SearchTorpedo,
    cLightType_LarryFlame,
    cLightType_IggyFlameRed,
    cLightType_IggyFlameGreen,
    cLightType_LudwigFlame,
    cLightType_BossKKThunder,
    cLightType_Woogan,
    cLightType_WendyRing,
    cLightType_LemmyBombExplosion,
    cLightType_KoopaElectricWire,
    cLightType_KoopaFlame,
    cLightType_FinalKoopaFlame,
    cLightType_FinalKoopaJrFlame,
    cLightType_LavaSurface,
    cLightType_PoisonWaterSurface,
    cLightType_StarLiftS,
    cLightType_StarLiftM,
    cLightType_StarLiftL,
    cLightType_Killer, // & SearchKiller
    cLightType_MagnumKiller, // & MagnumSearchKiller
    cLightType_KingKiller,
    cLightType_Woochan,
    cLightType_KazanRockBig,
    cLightType_KameckIce,
    cLightType_KameckMagic,
    cLightType_KoopaDoorCandle_LeftRight,
    cLightType_KoopaDoorCandle_Center,
    cLightType_KoopaSwitch,
    cLightType_KeronpaExplosion,
    cLightType_KeronpaTail,
    cLightType_ElectricWireShock,
};
